version: "3.9"
services:
  zincsearch:
    image: public.ecr.aws/zinclabs/zincsearch:latest
    ports:
      - "4080:4080"
    environment:
      - ZINC_FIRST_ADMIN_USER=admin
      - ZINC_FIRST_ADMIN_PASSWORD=Complexpass#123
    volumes:
      - zincsearch-data:/data
  indexer:
    build: ./indexer
    links:
      - zincsearch
    depends_on:
      - zincsearch
  back:
    build: ./gloryemail-back
    ports:
      - "3000:3000"
    links:
      - zincsearch
  front:
    build: ./gloryemail-front
    links:
      - back
    ports:
      - "4000:80"
volumes:
  zincsearch-data:
  
  
  

